### ISSUE TITLE
“Fatal Error” after Install and Activation

### ISSUE THREAD

**Issue by shamansun** [ansonphong/ArtDroid#3]
Hey Phong,

Love the look of the theme. Tried to install it on my Wordpress blog, but got this (below). Hope this helps smooth out any initial hiccups:

> Howdy!
> 
> Since WordPress 5.2 there is a built-in feature that detects when a plugin or theme causes a fatal error on your site, and notifies you with this automated email.
> 
> In this case, WordPress caught an error with your theme, ArtDroid.

> When seeking help with this issue, you may be asked for some of the following information:
> WordPress version 5.3.2
> Current theme: ArtDroid (version 1.4.52)
> Current plugin:  (version )
> PHP version 7.2.24

> 
> Error Details
> =============
> An error of type E_ERROR was caused in line 7 of the file /home/jdj_mutations/mutations.blog/wp-content/themes/ArtDroid-master/php/post-type-blog.php. Error message: Uncaught Error: Call to undefined function pw_get_option() in /home/jdj_mutations/mutations.blog/wp-content/themes/ArtDroid-master/php/post-type-blog.php:7
> Stack trace:
> #0 /home/jdj_mutations/mutations.blog/wp-content/themes/ArtDroid-master/php/post-type-blog.php(13): theme_blog_enabled()
> #1 /home/jdj_mutations/mutations.blog/wp-content/themes/ArtDroid-master/functions.php(120): include('/home/jdj_mutat...')
> #2 /home/jdj_mutations/mutations.blog/wp-settings.php(497): include('/home/jdj_mutat...')
> #3 /home/jdj_mutations/mutations.blog/wp-config.php(108): require_once('/home/jdj_mutat...')
> #4 /home/jdj_mutations/mutations.blog/wp-load.php(37): require_once('/home/jdj_mutat...')
> #5 /home/jdj_mutations/mutations.blog/wp-admin/admin.php(34): require_once('/home/jdj_mutat...')
> #6 /home/jdj_mutations/mutations.blog/wp-admin/customize.php(13): require_once('/home/jdj_mutat...')
> #7 {main}
>   thrown
>

**Comment by ansonphong** [comment]
@shamansun Thanks for the feedback. I posted an updated release (1.5.1) which I expect fixes this issue. Let me know if it's still persistant.

[Artdroid 1.5.1 Release](https://github.com/ansonphong/ArtDroid/releases/tag/1.5.1)
